package entity;
// Generated 6 ��� 2021 �., 17:26:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "groups",
        schema = "public"
)
public class Groups implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "group_id", unique = true, nullable = false)
    private int groupId;

    @Column(name = "group_name", nullable = false)
    private String groupName;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
    private Set<TimetableIate> timetableIates = new HashSet(0);

    public Groups() {
    }

    public Groups(int groupId, String groupName) {
        this.groupId = groupId;
        this.groupName = groupName;
    }

    public Groups(int groupId, String groupName, Set<TimetableIate> timetableIates) {
        this.groupId = groupId;
        this.groupName = groupName;
        this.timetableIates = timetableIates;
    }

    public int getGroupId() {
        return this.groupId;
    }

    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }

    public String getGroupName() {
        return this.groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public Set<TimetableIate> getTimetableIates() {
        return this.timetableIates;
    }

    public void setTimetableIates(Set<TimetableIate> timetableIates) {
        this.timetableIates = timetableIates;
    }

}
